sudo: true
language: python
python:
- '3.6'
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_f47eeffde8d5_key -iv $encrypted_f47eeffde8d5_iv
  -in .env.enc -out .env -d
install:
- pip install -r requirements/ci.txt
script:
- make test
after_success:
- make build-production-image publish-image
